Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace DACS_DAMH.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/MenuController.cs
using DACS_DAMH.Models;
using DACS_DAMH.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DACS_DAMH.Controllers
{
    public class MenuController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ApplicationDbContext _context;

        public MenuController(IProductRepository productRepository, ApplicationDbContext context)
        {
            _productRepository = productRepository;
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var products = await _context.Products
                                  .Include(p => p.Category)
                                  .ToListAsync();

            var groupedProducts = products.GroupBy(p => p.Category.Name)
                                          .Select(g => new CategoryProducts
                                          {
                                              CategoryName = g.Key,
                                              Products = g.ToList()
                                          })
                                          .OrderBy(vm => vm.CategoryName)
                                          .ToList();



            return View(groupedProducts);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Categoryproduct(string categoryName)
        {
            //var products = await _context.Products
            //                 .Include(p => p.Category)
            //                 .Where(p => p.Category.Name.Contains(categoryName))
            //                 .ToListAsync();            
            //return View(products);

            var products = await _context.Products
                                  .Include(p => p.Category)
                                  .Where(p => p.Category.Name.Contains(categoryName))
                                  .ToListAsync();

            var groupedProducts = products.GroupBy(p => p.Category.Name)
                                          .Select(g => new CategoryProducts
                                          {
                                              CategoryName = g.Key,
                                              Products = g.ToList()
                                          })
                                          .OrderBy(vm => vm.CategoryName)
                                          .ToList();

            

            return View(groupedProducts);
        }
    }
}

Views/Shared/Login_page.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/274025e879.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/Login_Register.css">
</head>
<body>
    <div class="container" id="container">

        @RenderBody()
        
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @* <script src="~/js/Login_Register.js"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <title>COFFEE RACER</title>
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="~/css/User-css.css">
    <link rel="stylesheet" href="~/css/tea.scss.css">
</head>

<body>

    <header>
        <div class="container">
            <div class="header_nav">
                <div class="header_logo">
                    <h1 style="padding-top:5px">
                        <a class="logo-name" href="/" title="The Coffee Racer">The Coffee Racer</a>
                    </h1>
                </div>

                <div class="header_menu" style="padding-left: 30px">
                    <div class="close-btn-wrap">
                        <a href="" class="closemenu-mobile">
                            <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M7.00023 5.58599L11.9502 0.635986L13.3642 2.04999L8.41423 6.99999L13.3642 11.95L11.9502 13.364L7.00023 8.41399L2.05023 13.364L0.63623 11.95L5.58623 6.99999L0.63623 2.04999L2.05023 0.635986L7.00023 5.58599Z" fill="black" fill-opacity="0.85"></path>
                            </svg>
                        </a>
                    </div>
                    <ul class="clearfix">
                        <li>
                            <a asp-area="" asp-controller="Product" asp-action="NavMenu" asp-route-categoryName="Cafe" title="Cà phê">Cà phê</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Product" asp-action="NavMenu" asp-route-categoryName="Trà" title="Trà">Trà</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Menu" asp-action="Index" title="Menu">Menu</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Blog" asp-action="Index" title="Chuyện Nhà">Chuyện Nhà</a>
                        </li>
                    </ul>
                </div>
                @*nhúng Icon giỏ hàng vào giao diện*@

                <div class="header_user">

                    <partial name="_LoginPartial" />

                    <form style="position: fixed;top: 15px;right: 120px;">
                        <button class="btn btn-outline-danger btn-lg" type="submit" asp-area="" asp-controller="ShoppingCart" asp-action="Index">
                            <i class="bi-cart-fill me-1"></i>
                            <span class="badge bg-danger text-white" id="badge-cart">0</span>

                        </button>
                    </form>

                </div>
            </div>
        </div>
    </header>

    <div class="row">
        <div id="demo" class="carousel slide" data-bs-ride="carousel">

            <!-- Indicators/dots -->
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
                <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
            </div>

            <!-- The slideshow/carousel -->
            <div class="carousel-inner ">
                <div class="carousel-item c-item active ">
                    <img src="https://file.hstatic.net/1000075078/file/web_desktop_1046f53e0b804a159ed93e6cc0548263.jpg" alt="Los Angeles" class="d-block c-img" @* style="width:100%; height:600px" *@>
                </div>
                <div class="carousel-item c-item">
                    <img src="https://file.hstatic.net/1000075078/file/web_moi_-_desktop_f6262a8c178b4bada6b90a9a4a845ee4.jpg" alt="Chicago" class="d-block c-img" @* style="width:100%; height:600px" *@>
                </div>
            </div>

            <!-- Left and right controls/icons -->
            <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
                <span class="carousel-control-next-icon"></span>
            </button>
        </div>
    </div>

    <div class="container" style="padding : 25px">
        <div class="row">
            <div class="clearfix">
                @RenderBody()
            </div>
        </div>
    </div>

    <section class="cloudtea index">
        <div class="cloudtea-block right">
            <div class="container">
                <div class="row flex-box flex-w align-c justify-s">
                    <div class="info-block">
                        <div class="img-title"><img src="https://file.hstatic.net/1000075078/file/tagline__1__1_378410beecb347f38cf8425ef7459690.png" alt="123123"></div>
                        <div class="cloudtea-desc">
                            Được trồng trọt và chăm chút kỹ lưỡng, nuôi dưỡng từ thổ nhưỡng phì nhiêu, nguồn nước mát lành, bao bọc bởi mây và sương cùng nền nhiệt độ mát mẻ quanh năm, những búp trà ở Tây Bắc mập mạp và xanh mướt, hội tụ đầy đủ dưỡng chất, sinh khí, và tinh hoa đất trời.

                            Chính khí hậu đặc trưng cùng phương pháp canh tác của đồng bào dân tộc nơi đây đã tạo ra Trà Xanh vị mộc dễ uống, dễ yêu, không thể trộn lẫn với bất kỳ vùng miền nào khác.
                        </div>

                    </div>
                    <div class="img-block">
                        <img src="">
                    </div>
                </div>
            </div>
        </div>

    </section>
    </br>

    </br>

    <footer id="footer" style="padding-top:25px">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 col-lg-push-6 col-md-push-6 footer_col">
                    <div class="hotline_footer">
                        <p><img src="https://file.hstatic.net/1000075078/file/phone_0a42df1c753c4fa0910108daa73fe2ef.png">Đặt hàng: 1999.9999</p><p><img src="https://file.hstatic.net/1000075078/file/map-pin-2-line_575ccb91b6f94a308d1bd507d4ae72a7.png">Liên hệ</p>
                    </div>
                    <div class="address_footer">
                        <p>Tầng 3-4 Hub Building <br> 195/10E Điện Biên Phủ, P.15,<br> Q.Bình Thạnh, TP.Hồ Chí Minh</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 col-lg-push-6 col-md-push-6 footer_col footer_right">

                    <ul class="tch_social_links">
                        <li>
                            <a href="https://www.facebook.com/The.Coffee.House.2014/">
                                <img src="https://file.hstatic.net/1000075078/file/test_fd4e30831d14438f9d0f1fcf255dfadb.svg">
                            </a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/thecoffeehousevn/">
                                <img src="https://file.hstatic.net/1000075078/file/test_db37bb3840ac45f3a0a3cf7aa8a57d9e.svg">
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-lg-pull-6 col-md-pull-6 footer_col">
                    <h3 class="footer_title">Giới thiệu</h3>                <ul class="footer_linklists">
                        <li><a href="/pages/chuyen-ca-phe-va-tra" title="Về Chúng Tôi">Về Chúng Tôi</a></li>
                        <li><a href="/" title="Sản phẩm">Sản phẩm</a></li>
                        <li><a href="/" title="Khuyến mãi">Khuyến mãi</a></li>
                        <li><a href="/pages/hat-ca-phe-the-coffee-house" title="Chuyện cà phê">Chuyện cà phê</a></li>
                        <li><a href="/pages/our-stores" title="Cửa Hàng">Cửa Hàng</a></li>
                        <li><a href="http://tuyendung.thecoffeehouse.com/" title="Tuyển dụng">Tuyển dụng</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-lg-pull-6 col-md-pull-6 footer_col">
                    <h3 class="footer_title">Điều khoản</h3>                <ul class="footer_linklists">
                        <li><a href="/pages/dieu-khoan-su-dung" title="Điều khoản sử dụng">Điều khoản sử dụng</a></li>
                        <li><a href="/pages/chinh-sach-bao-mat-thong-tin" title="Chính sách bảo mật thông tin">Chính sách bảo mật thông tin</a></li>
                        <li><a href="/pages/huong-dan-xuat-hoa-don-gtgt" title="Hướng dẫn xuất hóa đơn GTGT">Hướng dẫn xuất hóa đơn GTGT</a></li>
                    </ul>
                </div>

            </div>
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 footer_col">
                    <hr>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12 footer_col">
                    <ul class="footer_itemlists">
                        <li>Công ty cổ phần thương mại dịch vụ Trà Cà Phê VN</li>
                        <li>Mã số DN: 0312867172 do sở kế hoạch và đầu tư tp. HCM cấp ngày 23/07/2014. Người đại diện: NGÔ NGUYÊN KHA</li>
                        <li>Địa chỉ: 86-88 Cao Thắng, phường 04, quận 3, tp Hồ Chí Minh &nbsp; Điện thoại: (028) 7107 8079 &nbsp; Email: hi@thecoffeehouse.vn</li>
                        <li>© 2014-2022 Công ty cổ phần thương mại dịch vụ Trà Cà Phê VN mọi quyền bảo lưu</li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/_content/CurrieTechnologies.Razor.SweetAlert2/sweetAlert2.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
    <script>
        $(document).ready(function () {
            loadData();
            function loadData() {
                $.ajax({
                    url: '@Url.Action("IndexAJAX", "ShoppingCart")',
                    type: 'GET',
                    success: function (data) {
                        if (data && data.success && data.data) {
                            $("#badge-cart").html(data.data);
                        }
                    },

                });
            }
            $('.add-to-cart-btn').click(function (e) {
                e.preventDefault();
                var productId = $(this).siblings('.Id-input').val();
                var quantity = $(this).siblings('.quantity-input').val();
                $.ajax({
                    url: '@Url.Action("AddToCart", "ShoppingCart")',
                    type: 'POST',
                    data: { productId: productId, quantity: 1, updatedPrice: 0, sizeId: 2, toppingId: 4 },
                    success: function (data) {
                        if (data && data.success && data.data) {
                            $("#badge-cart").html(data.data);
                        }
                        Swal.fire({
                            position: "center",
                            icon: "success",
                            title: "Sản phẩm đã được thêm vào giỏ hàng.",
                            showConfirmButton: false,
                            timer: 1500,

                        });
                    },
                    error: function () {
                        Swal.fire({
                            icon: "error",
                            title: "Oops...",
                            text: "Vui lòng đăng nhập để tiếp tục!",
                            heightAuto: true

                        });
                    }

                });
            });
        });
    </script>
    <script>
        function menuToggle() {
            const toggleMenu = document.querySelector(".menu");
            toggleMenu.classList.toggle("active");
        }
    </script>
</body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <title>COFFEE RACER</title>
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="~/css/User-css.css">
    @* <link rel="stylesheet" href="~/css/checkout.css"> *@
</head>

<body>

    <header>
        <div class="container">
            <div class="header_nav">
                <div class="header_logo">
                    <h1 style="padding-top:5px">
                        <a class="logo-name" href="/" title="The Coffee Racer">The Coffee Racer</a>
                    </h1>
                </div>

                <div class="header_menu" style="padding-left: 30px">
                    <div class="close-btn-wrap">
                        <a href="" class="closemenu-mobile">
                            <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M7.00023 5.58599L11.9502 0.635986L13.3642 2.04999L8.41423 6.99999L13.3642 11.95L11.9502 13.364L7.00023 8.41399L2.05023 13.364L0.63623 11.95L5.58623 6.99999L0.63623 2.04999L2.05023 0.635986L7.00023 5.58599Z" fill="black" fill-opacity="0.85"></path>
                            </svg>
                        </a>
                    </div>
                    <ul class="clearfix">
                        <li>
                            <a asp-area="" asp-controller="Product" asp-action="NavMenu" asp-route-categoryName="Cafe" title="Cà phê">Cà phê</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Product" asp-action="NavMenu" asp-route-categoryName="Trà" title="Trà">Trà</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Menu" asp-action="Index" title="Menu">Menu</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Blog" asp-action="Index" title="Chuyện Nhà">Chuyện Nhà</a>
                        </li>
                    </ul>
                </div>
                @*nhúng Icon giỏ hàng vào giao diện*@

                <div class="header_user">

                    <partial name="_LoginPartial" />

                    <form style="position: fixed;top: 15px;right: 120px;">
                        <button class="btn btn-outline-danger btn-lg" type="submit" asp-area="" asp-controller="ShoppingCart" asp-action="Index">
                            <i class="bi-cart-fill me-1"></i>
                            <span class="badge bg-danger text-white" id="badge-cart">0</span>

                        </button>
                    </form>

                </div>
            </div>
        </div>
    </header>

    <div class="container" style="padding : 25px">
        <div class="row">
            <div class="clearfix">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer id="footer" style="padding-top:25px">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 col-lg-push-6 col-md-push-6 footer_col">
                    <div class="hotline_footer">
                        <p><img src="https://file.hstatic.net/1000075078/file/phone_0a42df1c753c4fa0910108daa73fe2ef.png">Đặt hàng: 1999.9999</p><p><img src="https://file.hstatic.net/1000075078/file/map-pin-2-line_575ccb91b6f94a308d1bd507d4ae72a7.png">Liên hệ</p>
                    </div>
                    <div class="address_footer">
                        <p>Tầng 3-4 Hub Building <br> 195/10E Điện Biên Phủ, P.15,<br> Q.Bình Thạnh, TP.Hồ Chí Minh</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 col-lg-push-6 col-md-push-6 footer_col footer_right">


                    <ul class="tch_social_links">
                        <li>
                            <a href="https://www.facebook.com/The.Coffee.House.2014/">
                                <img src="https://file.hstatic.net/1000075078/file/test_fd4e30831d14438f9d0f1fcf255dfadb.svg">
                            </a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/thecoffeehousevn/">
                                <img src="https://file.hstatic.net/1000075078/file/test_db37bb3840ac45f3a0a3cf7aa8a57d9e.svg">
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-lg-pull-6 col-md-pull-6 footer_col">
                    <h3 class="footer_title">Giới thiệu</h3>                <ul class="footer_linklists">
                        <li><a href="/pages/chuyen-ca-phe-va-tra" title="Về Chúng Tôi">Về Chúng Tôi</a></li>
                        <li><a href="/" title="Sản phẩm">Sản phẩm</a></li>
                        <li><a href="/" title="Khuyến mãi">Khuyến mãi</a></li>
                        <li><a href="/pages/hat-ca-phe-the-coffee-house" title="Chuyện cà phê">Chuyện cà phê</a></li>
                        <li><a href="/pages/our-stores" title="Cửa Hàng">Cửa Hàng</a></li>
                        <li><a href="http://tuyendung.thecoffeehouse.com/" title="Tuyển dụng">Tuyển dụng</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-lg-pull-6 col-md-pull-6 footer_col">
                    <h3 class="footer_title">Điều khoản</h3>                <ul class="footer_linklists">
                        <li><a href="/pages/dieu-khoan-su-dung" title="Điều khoản sử dụng">Điều khoản sử dụng</a></li>
                        <li><a href="/pages/chinh-sach-bao-mat-thong-tin" title="Chính sách bảo mật thông tin">Chính sách bảo mật thông tin</a></li>
                        <li><a href="/pages/huong-dan-xuat-hoa-don-gtgt" title="Hướng dẫn xuất hóa đơn GTGT">Hướng dẫn xuất hóa đơn GTGT</a></li>
                    </ul>
                </div>

            </div>
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 footer_col">
                    <hr>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12 footer_col">
                    <ul class="footer_itemlists">
                        <li>Công ty cổ phần thương mại dịch vụ Trà Cà Phê VN</li>
                        <li>Mã số DN: 0312867172 do sở kế hoạch và đầu tư tp. HCM cấp ngày 23/07/2014. Người đại diện: NGÔ NGUYÊN KHA</li>
                        <li>Địa chỉ: 86-88 Cao Thắng, phường 04, quận 3, tp Hồ Chí Minh &nbsp; Điện thoại: (028) 7107 8079 &nbsp; Email: hi@thecoffeehouse.vn</li>
                        <li>© 2014-2022 Công ty cổ phần thương mại dịch vụ Trà Cà Phê VN mọi quyền bảo lưu</li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/_content/CurrieTechnologies.Razor.SweetAlert2/sweetAlert2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        function menuToggle() {
            const toggleMenu = document.querySelector(".menu");
            toggleMenu.classList.toggle("active");
        }
    </script>
</body>
</html>

Views/Shared/_SubMenuItem.cshtml
@model NavigationItemViewModel

@* <li>
    <a href="@Model.Url">@Model.Name</a>
    @if (Model.HasChildren)
    {
        <ul>
            @foreach (var childItem in Model.Children)
            {
                <partial name="_SubMenuItem" model="childItem" />
            }
        </ul>
    }
</li> *@

<li class="menu_dropdown">
    <a href="@Model.Url">@Model.Name</a>

    @if (Model.HasChildren)
    {
        <ul class="menu_lv2">
            @foreach (var childItem in Model.Children)
            {
               
                <partial name="_SubMenuItem" model="childItem" />
                
            }
        </ul>
    }
</li>